apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  labels:
    app: content-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: acrk8swth2.azurecr.io/content-api:v1
        resources:
          requests:
            cpu: "128m"
            memory: "128Mi"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: content-api-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: content-api